name: Update 24SevenOffice API Documentation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows for manual triggering

jobs:
  update-api-doc:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the update_api_doc.py script
      - name: Update API Documentation
        run: |
          python update_api_doc.py

      # Commit and push the updated API documentation to the repository
      - name: Commit updated API documentation
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add 24SevenOfficeAPI.json
          git commit -m "Update 24SevenOffice API documentation"
          git push
