name: Update 24SevenOffice API Documentation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows for manual triggering
  push:
    branches:
      - main

jobs:
  update-api-doc:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Skip workflow if the commit was made by GitHub Actions bot
      - name: Skip if committed by GitHub Actions bot
        run: |
          COMMITTER=$(git log -1 --pretty=format:'%an')
          if [ "$COMMITTER" = "github-actions[bot]" ]; then
            echo "Workflow triggered by github-actions[bot], exiting..."
            exit 0
          fi

      # Set GITHUB_TOKEN as an environment variable so it's accessible in the Python script
      - name: Set up environment with GITHUB_TOKEN
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the update_api_doc.py script
      - name: Run Python script and update API Documentation
        run: python update_api_doc.py

      # Check if there are changes in the 24SevenOfficeAPI.json file
      - name: Check for changes
        id: check_changes
        run: |
          git fetch
          git diff --exit-code 24SevenOfficeAPI.json || echo "has_changes=true" >> $GITHUB_ENV

      # Commit and push the updated API documentation (24SevenOfficeAPI.json) to the repository if changes exist
      - name: Commit updated API documentation
        if: env.has_changes == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add 24SevenOfficeAPI.json
          git commit -m "Update 24SevenOffice API documentation"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
