name: Update 24SevenOffice API Documentation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows for manual triggering
  push:
    branches:
      - main
    paths-ignore:  # Ignore changes that the workflow itself commits
      - "24SevenOfficeAPI.json"  # This prevents the workflow from triggering on this file

jobs:
  update-api-doc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment with GITHUB_TOKEN
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script and update API Documentation
        run: python update_api_doc.py

      - name: Check for changes
        id: check_changes
        run: |
          git fetch
          git diff --exit-code 24SevenOfficeAPI.json || echo "has_changes=true" >> $GITHUB_ENV

      - name: Commit updated API documentation
        if: env.has_changes == 'true'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add 24SevenOfficeAPI.json
          git commit -m "Update 24SevenOffice API documentation"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
